feat: clean up children parsing
pln-planning-tools/MapLight pull request #379
Opened 2023-07-01 01:27 UTC by SgtPooki

- feat: add string utility functions
- test(getChildren): add assertions on children urls
- feat: migrate more parser functions to betweenTwoRegex
- docs(user-guide): add FAQs, Legend, and more info about children parsing
- test(parser-bug378): add fixture

fixes #378

* User Guide updates
  * Add FAQs section
  * Add Legend section
  * Add FAQ entry about children not rendering
  * Add more visual awareness to the deprecation and requirements for "children:" syntax.
  * Fix header rendering so that headings can be deep-linked (similar to viewing markdown files on github)
* lib/parser.ts updates
  * Break out some section parsing logic into lib/utils/strings.ts
  * Add test for #378
  * Add tests for lib/utils/strings.ts
  * Add assertions for parser.test.ts children url assertions

2023-07-01 02:06 UTC, SgtPooki commented
https://starmaps-git-378-bug-filecoin-stationroadmap-cea790-ipfs-ignite.vercel.app/roadmap/github.com/filecoin-station/roadmap/issues/19#view=simple is currently showing client side error... looking into it

2023-07-01 03:13 UTC, whizzzkid requested changes
I think complexity can be reduced.

2023-07-02 03:37 UTC, SgtPooki commented on lib/utils/strings.ts
> +  if (index2 === -1) {
the second inde is only set on the substring of the portion of the original string occurring after the first inde.

2023-07-02 03:56 UTC, SgtPooki commented on lib/utils/strings.ts
> +}
I will try to run your regex against the tests and see if it passes.

This change doesn't allow two arbitrary regex expressions with their flags and whatnot. There may be fewer lines and a more direct capturing of the middle, but it increases complexity by requiring users to be intimately familiar with how their regex will combine. 

The existing code is explicit in that the first and last regex are simply cursors, and the result is everything in-between. It's also straightforward to understand.

There are some use cases on multiline regex where controlling the flags separately for the first and last cursor separately can help increase flexibility without requiring regex foo.

2023-07-02 03:58 UTC, SgtPooki commented on lib/utils/strings.ts
> +  const startMatchStr = result1[0]
because of the way the regex match result is constructed, this required additional type assertions.

2023-07-03 20:00 UTC, SgtPooki commented on lib/utils/strings.ts
> +}
yea, a lot of tests are failing with similar changes:

```ts
  const regex = new RegExp(`${regex1}(?<needed>.+?)${regex2}`, 'ig')
  const regexResult = regex.exec(str)
  if (regexResult == null) {
    throw new Error(`Could not find '${regex}' in string`)
  }
  if (!regexResult.groups) {
    throw new Error(`Could not find 'needed' group in '${regex}'`)
  }
  const { groups: { needed } } = regexResult
  return needed 
```

Some errors (out of 20 failures):

* strings › betweenTwoRegex › works on single lines -> `Could not find '/\/hello\/(?<needed>.+?)\/world\//gim' in string`
* strings › betweenTwoRegex › works on complicated multiple line strings -> `Could not find '/\/hello\/(?<needed>.+?)\/goodbye\//gim' in string`


Another issue with combining the regex (though it's an intuitive response) is that users have to submit either only regex strings (not actual regex) or partial regex (no endings on starting cursor, no starts on ending cursor).

I think this change would significantly increase complexity while requiring much more maintenance overhead for the function itself (handling edge-cases) and users (figuring out how to work with the combined regex)

2023-07-04 16:05 UTC, whizzzkid approved these changes
thanks for the explainers.

2023-07-04 18:04 UTC, merged